name: Code Linting

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    name: Lint Debug Variant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lintDebug

      - name: Upload Lint Results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: |
            app/build/reports/lint/
            app/build/outputs/lint/
          if-no-files-found: ignore
          retention-days: 7

      - name: Check Lint Results
        run: |
          if [ -f "app/build/reports/lint-results.txt" ]; then
            echo "Lint report generated"
            cat app/build/reports/lint-results.txt | head -10
          else
            echo "No lint results file found - checking alternative locations"
            find . -name "*lint*" -type f | head -5
          fi